/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_suren_autotest_webdriver_downloader_NativeProgress */

#ifndef _Included_org_suren_autotest_webdriver_downloader_NativeProgress
#define _Included_org_suren_autotest_webdriver_downloader_NativeProgress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_suren_autotest_webdriver_downloader_NativeProgress
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_suren_autotest_webdriver_downloader_NativeProgress_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
